# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test Release Branch of Url Shortener

on:
  push:
    branches:
      - 'Release*'  # Matches any branch starting with 'Release'
      - 'FT-102-alias-with-url-mapping-repository'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Lint with Checkstyle
      run: mvn checkstyle:checkstyle
      continue-on-error: true

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run tests
      run: mvn test
